name: Reports

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'docs/**'

jobs:
  build:
    name: Build Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: failgood/failgood
          path: failgood
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: ./gradlew buildHealth
        working-directory:
          main
      - name: Comment PR
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const path = 'build/reports/dependency-analysis/build-health-report.txt'
            const fs = require('fs')
            if (!fs.existsSync(path)) {
              console.error('Generated file not found!');
              process.exit(1);
            }
            const fileContent = fs.readFileSync(path, 'utf8')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '```\n' + fileContent + '\n```'
            })
