name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: pitest on jdk 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        continue-on-error: true
        env:
          CI: true
          PITEST_THREADS: 2
        run: ./gradlew pitest
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-reports-pitest
          path: "**/build/reports"
